#!/usr/bin/env bash
#fizzbuzz from 1 to 100
c=1

while [ $c -le 100 ]; do
	if (( c % 3 == 0 )) && (( c % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( c % 3 == 0 )); then
		echo "Fizz"
	elif (( c % 5 == 0 )); then
		echo "Buzz"
	else
		echo $c
	fi

	(( c++ ))
done

